# Generated by Django 5.1 on 2024-08-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_image_download', '0002_carnumberplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnumberplate',
            name='image',
        ),
    ]
