# Generated by Django 5.1 on 2024-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0008_alter_userfoldergoogledrive_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfoldergoogledrive",
            old_name="user",
            new_name="user_ids",
        ),
    ]
