# Generated by Django 5.1 on 2024-08-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parking_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_start', models.DateTimeField(auto_now_add=True)),
                ('parking_end', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings_history', to='parkings.plates')),
            ],
        ),
    ]
